apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: 179266296566.dkr.ecr.us-west-1.amazonaws.com/client
          ports:
            - containerPort: 3000
