apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    run: client
spec:
  selector:
    app: client
  ports:
    - name: client
      port: 3000
      targetPort: 3000
      protocol: TCP
