apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    run: server
spec:
  selector:
    app: server
  ports:
    - name: server
      port: 5000
      targetPort: 5000
      protocol: TCP
